export const blogs = [
  {
    id: 10,
    title: 'Making Cents Of Your Energy',
    content:
      "## Making Cents Of Your Energy\n\n*Summer 2022*\n\n With rising energy costs a seemingly inevitable, and our homes becoming more electrified than ever, it's a great time to review how you use energy, and how to make the most cents out of it. \n\nThe Maine Public Utilities Commission is the overseeing body which assists consumers, as well as locally-owned, or investor-owned utility companies set delivery rates and energy costs to the end user. Back in 2019 Central Maine power announced expected rate increases for \"the next three years.\" True to the announcement. customers within their respective electric utilities, have seen annual rate increases. Central Maine Power Customer for example have seen the average total rate per kWh increase from roughly 16.3¢(in 2018) to 21.1¢/kWh as of December 31 2021*\n\nIn a state with somewhat aging infrastructure and cyclical weather patterns, it should also be expected that the cost of energy, not just electricity, will continue to increase(i.e. gas, oil, water, other). As the sources become more expensive, difficult to obtain, and more finite over time. The demand,  regardless of the energy mix, is expected to increase as well, and it's worth having a few tools to hedge against the future.\n\n#### Resources to Help You Become More Energy Independent\n\n*Devices and Tools*\n\n**The Sense Device**\n\nOne great device to help you be aware of how you're using energy(electricity), where you're using it, and if you're getting the right reading from your utility meter on your bill is The *Sense*, and *Sense Solar* Devices. \nThese devices can give you a clear picture of what you're using for energy - through their machine learning and AI tech, the Sense devices can tell you what loads are using the most, what loads are using the least, and they can even tell you based on historical data if a device might be in need of retirement and replacement.\nIf you are producing power at your home, via a solar array or even a generator, the Sense Solar Device can recognize and give you a better picture of your production and the energy offset it provides to you.\nThis is all on one, easy-to-use, and easy to understand app that provides you with periodic and real-time data at the palm of your hand while also having the ability to communicate with devices throughout your home using the IFTTT protocol such as your **Amazon Alexa**, **Wemo**, and **TP Link Kasa** to name a few.\n\n**Span**\n\nThe Span smart panel provides a smart panel upgrade for the energy and load-conscious homeowner. Pre-built to be breaker-agnostic, with additional preset positions for your solar, battery backup, or other loads. This update to the main service or \"breaker\" panel is Wi-Fi enabled, and able to provide you with automated or preconfigured backup protocols - keeping some loads on, or turning some loads off in the event of an outage, while on backup power. \n\n\nSolar Power New England designs and installs solar photovoltaic systems for homeowners with built in production, and whole home consumption(if applicable) metering capabilities. Solar Power New England also installs Sense Metering Devices for customers. Solar Power New England is a Certified Span Installer. Contact us for more information, with your questions, and if you think solar, Span, Sense, or Sense Solar is a good fit for your home/project.\n\n[Contact Us To Learn More](mailto:contact@solarpowerne.com)\n\nFor More information on current and historic utility rates, please visit the [Maine PUC: Residential Electric Rates](https://www.maine.gov/mpuc/regulated-utilities/electricity/delivery-rates)\n\nProduct Link(s):\n[Sense, Sense Solar](https://sense.com/)\n[Span](https://www.solarpowernewengland.com/partners/span)",
    published_at: '2022-07-27T19:20:19.688Z',
    created_at: '2022-07-27T17:41:19.478Z',
    updated_at: '2022-07-27T19:20:19.712Z',
    slug: 'Making-Cents-Of-Your-Energy',
    ComingSoon: null,
    Tags: 'sense, energy monitoring, meters, solar, smart panel',
    Excerpt: null,
    image: {
      id: 103,
      name: "Sense-Energy-Monitor ' take command '.jpg",
      alternativeText: '',
      caption: '',
      width: 970,
      height: 300,
      formats: {
        small: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/robitaille/image/upload/v1658942716/small_Sense_Energy_Monitor_take_command_7a44661318.jpg',
          hash: 'small_Sense_Energy_Monitor_take_command_7a44661318',
          mime: 'image/jpeg',
          name: "small_Sense-Energy-Monitor ' take command '.jpg",
          path: null,
          size: 10.19,
          width: 500,
          height: 155,
          provider_metadata: {
            public_id:
              'small_Sense_Energy_Monitor_take_command_7a44661318',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/robitaille/image/upload/v1658942716/medium_Sense_Energy_Monitor_take_command_7a44661318.jpg',
          hash: 'medium_Sense_Energy_Monitor_take_command_7a44661318',
          mime: 'image/jpeg',
          name: "medium_Sense-Energy-Monitor ' take command '.jpg",
          path: null,
          size: 18.66,
          width: 750,
          height: 232,
          provider_metadata: {
            public_id:
              'medium_Sense_Energy_Monitor_take_command_7a44661318',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/robitaille/image/upload/v1658942715/thumbnail_Sense_Energy_Monitor_take_command_7a44661318.jpg',
          hash: 'thumbnail_Sense_Energy_Monitor_take_command_7a44661318',
          mime: 'image/jpeg',
          name: "thumbnail_Sense-Energy-Monitor ' take command '.jpg",
          path: null,
          size: 4.1,
          width: 245,
          height: 76,
          provider_metadata: {
            public_id:
              'thumbnail_Sense_Energy_Monitor_take_command_7a44661318',
            resource_type: 'image',
          },
        },
      },
      hash: 'Sense_Energy_Monitor_take_command_7a44661318',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 24.49,
      url: 'https://res.cloudinary.com/robitaille/image/upload/v1658942714/Sense_Energy_Monitor_take_command_7a44661318.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'Sense_Energy_Monitor_take_command_7a44661318',
        resource_type: 'image',
      },
      created_at: '2022-07-27T17:25:17.147Z',
      updated_at: '2022-07-27T17:25:17.197Z',
    },
  },
  {
    id: 9,
    title: 'Solar and Renewable Energy Incentives In Maine',
    content:
      "Solar and Renewable Energy Incentives In Maine: *Updated 2021*\n\nWhat a wild ride it has been in the solar industry, with end-of-year wins for both homeowners, and businesses alike! In this article, we will give you an overview of what you can expect, and how you can make the most informed decision in the coming months and years.\n\n*You’ve Been Considering Going Solar, This Might Be The Best Time To Do It, And Here’s Why*\n\n\n- Panel prices are currently the lowest they’ve ever been! Over the last 30+ years, [panel prices have dropped an astounding 90% in cost!](https://www.fastcompany.com/90583426/the-price-of-solar-electricity-has-dropped-89-in-10-years))\n- The Federal Tax Credit, commonly known as the [Residential Renewable Energy Investment Tax Credit](https://programs.dsireusa.org/system/program/detail/1235)(ITC), has been extended for 2 years! \n- Originally scheduled to drop from 26% to 22%, the tax credit is now extended at 26% until December 31, 2022 at which point it will drop to 22% until the end of 2023.\n- Property Taxes: Solar is now property tax exempt!\n\n*The 26% **Residential** Renewable Energy Investment Tax Credit, explained*\n\nSince 2005, the “Federal ITC” for Renewable Energy Investment Tax Credit, was established to encourage adoption of renewable energy systems in the U.S. Combined with price reductions in panels and other associated equipment - commonly referred to as “balance-of-system components,” this has brought the cost of solar down, making it more affordable for homeowners. And now, it’s cheaper than most other forms of fuel/energy. Per the IRS list of eligible equipment , the tax credit now also applies to battery-based systems, which are replenished by a solar photovoltaic array. \n\nITC Calendar For Residential Customers:\n- 26% for systems “commissioned” or turned-on before 01/01/2023\n- 22% for systems  installed and commissioned before 01/01/2024\n- A permanent 10% for all systems commissioned after 01/01/2024*\n\n\n*Renewable Energy Investment, Property Tax Exemption*\n\n*Why is no one talking about this one*!? One of the greatest wins for homeowners has come in the form of Property Tax Exemption with regards to your solar photovoltaic system. In 2019, Maine join dozens of state's in passing [Bill LD 1430](https://legislature.maine.gov/legis/bills/getPDF.asp?paper=HP1040&item=1&snum=129), introducing a solar tax exemption for both businesses and residential owners. Commonly referred to as the Renewable Energy Investment Exemption, Maine exempts renewable energy equipment purchased for your home, such as solar panels. In other words, your investment into your home builds in value for you, and you are exempt from Established in 2020, taxpayers must apply for the credit by April 1 of the first year the exemption is requested. \n\nIf you have an existing system, feel free to contact us here contact@solarpowerne.com and we will help you fill out the application. The Maine Revenue Service has now issued a standard application for the property tax exemption. [This form is also available for download here](https://www.maine.gov/revenue/sites/maine.gov.revenue/files/inline-files/solar_exempt_app.pdf).\n\nSolar Power New England provides full-service remote and on-site assessment, consultation, system design and installation of solar photovoltaics, electric vehicle charging stations, and energy management devices for homeowners, local businesses and individuals.\n\n![logo.png](https://res.cloudinary.com/robitaille/image/upload/v1610667594/logo_dd8899cb34.png)\n",
    published_at: '2021-04-27T00:13:09.479Z',
    created_at: '2021-01-27T19:37:14.925Z',
    updated_at: '2022-02-10T00:34:24.868Z',
    slug: 'solar-incentives-in-maine',
    ComingSoon: false,
    Tags: 'Solar, Finance',
    Excerpt: '',
    image: {
      id: 53,
      name: 'Solar-Panel-Rebates-Tax-Incentives-300x225.jpg',
      alternativeText: '',
      caption: '',
      width: 300,
      height: 225,
      formats: {
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/robitaille/image/upload/v1619481047/thumbnail_Solar_Panel_Rebates_Tax_Incentives_300x225_8e70190dce.jpg',
          hash: 'thumbnail_Solar_Panel_Rebates_Tax_Incentives_300x225_8e70190dce',
          mime: 'image/jpeg',
          name: 'thumbnail_Solar-Panel-Rebates-Tax-Incentives-300x225.jpg',
          path: null,
          size: 5.19,
          width: 208,
          height: 156,
          provider_metadata: {
            public_id:
              'thumbnail_Solar_Panel_Rebates_Tax_Incentives_300x225_8e70190dce',
            resource_type: 'image',
          },
        },
      },
      hash: 'Solar_Panel_Rebates_Tax_Incentives_300x225_8e70190dce',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 9.4,
      url: 'https://res.cloudinary.com/robitaille/image/upload/v1619481047/Solar_Panel_Rebates_Tax_Incentives_300x225_8e70190dce.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id:
          'Solar_Panel_Rebates_Tax_Incentives_300x225_8e70190dce',
        resource_type: 'image',
      },
      created_at: '2021-04-26T23:50:48.048Z',
      updated_at: '2021-04-26T23:50:48.059Z',
    },
  },
  {
    id: 7,
    title: 'Plug-In Electric Vehicle Rebates',
    content:
      "### Maine Electric Vehicle Rebates and Incentives  \n\nWhether it's trucks, cars, bicycles, trains, hyperloops or rockets; transportation is evolving and the future is here.\n\n\nMaine has welcomed incentives for solar and renewable energy, and has continued it's support for clean energy adoption in the form of transportation. Hybrid and Electric vehicles are now being built in varying forms and sizes from vehicles as large as the new [Tesla Semi](https://www.tesla.com/semi) and as compact as the [Toyota Prius](https://www.toyota.com/prius/). We'll cover here how the vehicle incentives and types differ, what applies, and how you can receive yours too.  \n\n### The Difference between Hybrids, Plug-In Hybrids, and EV's  \n  Breaking down vehicle incentives and offerings really comes down to the type of vehicle you are purchasing, however new and used (newer than 2015) vehicles both apply under Maine guidelines. Although there is an incentive in terms of fuel efficiency from hybrid vehicles, there are no additional rebates there, unless it can be refueled by electricity. \nIn other words, when we say 'Hybrid' vs. 'Plug-in Hybrid' - if your hybrid only runs on a gas motor or only recharges a large battery by either running the engine, while driving or some form of regenerative braking that won't meet the current guidelines. \n The new and used fleet of vehicles that may be eligible for rebates under Maine guidelines are coming in the form of the Battery Electric Vehicles(BEV's) and Plug-in Hybrid Vehicles(PHEV's), where BEV's are an all-electric vehicle and the PHEV's are able to be \"refueled\" by by gasoline, or electricity. \n\n### New Vehicles\n\nNew Battery Electric Vehicles(BEV's) and Plug-in Hybrid Vehicles(PHEV's) purchased by an individual, business or organization in Maine are eligible for a \"Standard Rebate.\" \n\n    New PHEV's = $1,000.00\n\n    New BEV's = $2,000.00   \n  \n  \n\n### Used Vehicles\n\n For Used Battery Electric Vehicles(BEV's) and Plug-in Hybrid Vehicles(PHEV's) income restrictions apply, however, individuals eligible may receive a $2,500 rebate on Used Vehicles, for New Battery Electric Vehicles, up to $5,500, Plug-in's $4,500.\n#### [New Vehicles Eligible for Rebates Through Efficiency Maine](https://www.efficiencymaine.com/docs/Eligibile-Vehicle-Rebates.pdf)\n\n#### [Used Vehicles Eligible for Rebates Through Efficiency Maine](https://www.efficiencymaine.com/docs/EV-Accelerator-Eligible-Used-EVs-List.pdf)\n\n### Solar Energy and Electric Vehicles\n  \"That's where it all ties together\" \n\nGasoline prices go up and down, mostly dictated by supply and demand from overseas. Imagine if all our vehicles were able to be charged up, right where they rest every evening. Well, we're there, and it took collective support. Solar photovoltaics are eligible for net-metering: in essence, in Maine, your local utility provider(CMP, Emera, KBLP) will bank the excess energy you produce right at home from your solar array. By providing your home with a local energy supply right on your roof, you a reducing any trips to a gas station, no more fumes, and the amount of energy used to create the vehicle is usually offset in 6-12months based on the typical annual average of the American consumer and over it's life cycle will produce far fewer pollutants than a typical gas, diesel or other fossil-fuel burning vehicle. As shown in this article by the Union of Concerned Scientists, in their word's, \"[Battery Electric Vehicles Are Cleaner From The Cradle To The Grave](https://blog.ucsusa.org/dave-reichmuth/are-electric-vehicles-really-better-for-the-climate-yes-heres-why?_ga=2.153920120.196094555.1611781507-469825618.1611781507)\"\n\nRebate forms, applications, and additional eligibility details may be found at [Efficiency Maine's Website](https://www.efficiencymaine.com/evehicles/electric-vehicle-rebates/). For more information about electric vehicle rebates, incentives, and how to integrate the technology into your home or business, contact us today.\n*List's updated December 2020*\n\n***Solar Power New England provides full-service remote and on-site assessment, consultation, system design and installation of solar photovoltaics, electric vehicle charging stations, and energy management devices for homeowners, local businesses and individuals.***\n![electric-cars-charging1500x900.jpg](https://res.cloudinary.com/robitaille/image/upload/v1611781893/electric_cars_charging1500x900_54e8a4cca5.jpg)",
    published_at: '2020-12-28T22:40:40.463Z',
    created_at: '2020-12-28T22:40:39.294Z',
    updated_at: '2022-01-25T22:13:40.031Z',
    slug: 'Plug-In-Electric-Vehicle-Rebates',
    ComingSoon: false,
    Tags: null,
    Excerpt: null,
    image: {
      id: 2,
      name: 'ca-times.brightspotcdn.com.jpg',
      alternativeText: '',
      caption: '',
      width: 840,
      height: 558,
      formats: {
        small: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/robitaille/image/upload/v1608739779/small_ca_times_brightspotcdn_com_a5be02351f.jpg',
          hash: 'small_ca_times_brightspotcdn_com_a5be02351f',
          mime: 'image/jpeg',
          name: 'small_ca-times.brightspotcdn.com.jpg',
          path: null,
          size: 23.36,
          width: 500,
          height: 332,
          provider_metadata: {
            public_id: 'small_ca_times_brightspotcdn_com_a5be02351f',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/robitaille/image/upload/v1608739778/medium_ca_times_brightspotcdn_com_a5be02351f.jpg',
          hash: 'medium_ca_times_brightspotcdn_com_a5be02351f',
          mime: 'image/jpeg',
          name: 'medium_ca-times.brightspotcdn.com.jpg',
          path: null,
          size: 42.14,
          width: 750,
          height: 498,
          provider_metadata: {
            public_id: 'medium_ca_times_brightspotcdn_com_a5be02351f',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/robitaille/image/upload/v1608739777/thumbnail_ca_times_brightspotcdn_com_a5be02351f.jpg',
          hash: 'thumbnail_ca_times_brightspotcdn_com_a5be02351f',
          mime: 'image/jpeg',
          name: 'thumbnail_ca-times.brightspotcdn.com.jpg',
          path: null,
          size: 8.25,
          width: 235,
          height: 156,
          provider_metadata: {
            public_id:
              'thumbnail_ca_times_brightspotcdn_com_a5be02351f',
            resource_type: 'image',
          },
        },
      },
      hash: 'ca_times_brightspotcdn_com_a5be02351f',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 50.37,
      url: 'https://res.cloudinary.com/robitaille/image/upload/v1608739777/ca_times_brightspotcdn_com_a5be02351f.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'ca_times_brightspotcdn_com_a5be02351f',
        resource_type: 'image',
      },
      created_at: '2020-12-23T16:09:39.542Z',
      updated_at: '2020-12-23T16:09:39.587Z',
    },
  },
  {
    id: 6,
    title: 'Other Ways You Can Be Sustainable',
    content:
      "Here in Maine, we're blessed to have a wealth of natural attractions from the coast to the end of the Appalachian trail. We can all be more efficient, sustainable, and conscious of our footprint. Here are a few ways you can improve your neighborhood, reduce your impact on the environment and help contribute to improving our community in an ecologically conscious manner.\n\n\n### Your Trash Can Be Your Treasure\n\n**Composting** can be a great way to bring life back into soil - utilizing food scraps, recycled paper products free of parabens or plastics, and even some forms of animal waste. There's a number of free online resources that we've found helpful from YouTube Videos or other, but there are also a number of locally owned companies you can connect with who will pick up those stinky peelings for you!\n\n *Garbage-To-Garden* curently offers pickup services for around $8.99/mth and $99.00/year - [see their website for more info](https://garbagetogarden.org/)\n\n*We Compost It!* is another great locally-owned business which has been serving homes and businesses alike for years. Their home location is in Auburn, Maine - but they provide similar composting services to most of Southern Maine. They also offer curbside Residential Composting and Pickup for around $8.99/mth. [See their website for more info](http://www.wecompostit.com/)\n\n*Mr. Fox Composting* is a Maine and New Hampshire based composting service, also specializing in curbside pickup for residential and commercial facilities. Their website is intuitive, and shows their serviceable areas somewhere from Wells-to-Kittery, Maine and from Portsmouth-to-Dover, New Hampshire. [Feel free to contact their company for more information.](https://mrfoxcomposting.com/)\n\n### *Cultivate* The Community You Hope For\n\nLast but surely not least, we wanted to showcase a company we've been a part of in the past, and still today, either through our own volunteer efforts, or with our employees having managed multiple community gardens, and grow-local initiatives. \n*Cultivating Community* is a fantastic organization which supports local gardening communities, immigrants, and they also support local school initiatives among many other activities. Whether you're young or old, you can reach out to them and find a way to volunteer, engage with all types of Mainers, buy their veggies & products through a \"farm-share,\" or other. [You can find more ways to get involved, donate, or volunteer here at their website.](https://www.cultivatingcommunity.org/)\n\n\n\n\n",
    published_at: '2020-12-28T22:40:22.067Z',
    created_at: '2020-12-28T22:40:20.985Z',
    updated_at: '2021-07-14T22:02:31.122Z',
    slug: 'Other-Ways-You-Can-Be-Sustainable',
    ComingSoon: false,
    Tags: null,
    Excerpt: null,
    image: {
      id: 4,
      name: '100-Simple-Tips-To-Live-a-More-Sustainable-Lifestyle-e1566537932796.jpg',
      alternativeText: '',
      caption: '',
      width: 900,
      height: 600,
      formats: {
        small: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/robitaille/image/upload/v1609194864/small_100_Simple_Tips_To_Live_a_More_Sustainable_Lifestyle_e1566537932796_c51bb9c432.jpg',
          hash: 'small_100_Simple_Tips_To_Live_a_More_Sustainable_Lifestyle_e1566537932796_c51bb9c432',
          mime: 'image/jpeg',
          name: 'small_100-Simple-Tips-To-Live-a-More-Sustainable-Lifestyle-e1566537932796.jpg',
          path: null,
          size: 18.14,
          width: 500,
          height: 333,
          provider_metadata: {
            public_id:
              'small_100_Simple_Tips_To_Live_a_More_Sustainable_Lifestyle_e1566537932796_c51bb9c432',
            resource_type: 'image',
          },
        },
        medium: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/robitaille/image/upload/v1609194863/medium_100_Simple_Tips_To_Live_a_More_Sustainable_Lifestyle_e1566537932796_c51bb9c432.jpg',
          hash: 'medium_100_Simple_Tips_To_Live_a_More_Sustainable_Lifestyle_e1566537932796_c51bb9c432',
          mime: 'image/jpeg',
          name: 'medium_100-Simple-Tips-To-Live-a-More-Sustainable-Lifestyle-e1566537932796.jpg',
          path: null,
          size: 32.1,
          width: 750,
          height: 500,
          provider_metadata: {
            public_id:
              'medium_100_Simple_Tips_To_Live_a_More_Sustainable_Lifestyle_e1566537932796_c51bb9c432',
            resource_type: 'image',
          },
        },
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/robitaille/image/upload/v1609194863/thumbnail_100_Simple_Tips_To_Live_a_More_Sustainable_Lifestyle_e1566537932796_c51bb9c432.jpg',
          hash: 'thumbnail_100_Simple_Tips_To_Live_a_More_Sustainable_Lifestyle_e1566537932796_c51bb9c432',
          mime: 'image/jpeg',
          name: 'thumbnail_100-Simple-Tips-To-Live-a-More-Sustainable-Lifestyle-e1566537932796.jpg',
          path: null,
          size: 6.3,
          width: 234,
          height: 156,
          provider_metadata: {
            public_id:
              'thumbnail_100_Simple_Tips_To_Live_a_More_Sustainable_Lifestyle_e1566537932796_c51bb9c432',
            resource_type: 'image',
          },
        },
      },
      hash: '100_Simple_Tips_To_Live_a_More_Sustainable_Lifestyle_e1566537932796_c51bb9c432',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 27.9,
      url: 'https://res.cloudinary.com/robitaille/image/upload/v1609194863/100_Simple_Tips_To_Live_a_More_Sustainable_Lifestyle_e1566537932796_c51bb9c432.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id:
          '100_Simple_Tips_To_Live_a_More_Sustainable_Lifestyle_e1566537932796_c51bb9c432',
        resource_type: 'image',
      },
      created_at: '2020-12-28T22:34:24.538Z',
      updated_at: '2020-12-28T22:34:24.556Z',
    },
  },
  {
    id: 5,
    title: 'Solar Power New England Makes Solar More Affordable',
    content:
      'We\'re excited to announce that we are expanding our ability to make solar more affordable, through our partnership and financing affiliate *Lighstream Financial* !\n\nLightStream makes Lending Uncomplicated®, with low rates and an easy online application.\nWhen you’re approved, you get quick funding, directly to your bank account.\n\nHave an idea of the cost already, or perhaps you\'ve firmed up your budget, and know what your needs are? Check rates through our affiliate [Link Here](https://www.lightstream.com/?fact=14854&amp;irad=618633&amp;irmp=2437142) or click the banner below to use their free "Solar Calculator" \n\nHave questions about your system options, or looking for a competitive, hassle-free, estimate from a local, Maine company? [Contact us today](mailto:contact@solarpowerne.com).\n\n',
    published_at: '2020-12-28T22:40:03.138Z',
    created_at: '2020-12-28T22:40:01.928Z',
    updated_at: '2021-07-14T21:27:31.116Z',
    slug: 'SPNE-Makes-Solar-More-Affordable',
    ComingSoon: false,
    Tags: null,
    Excerpt: null,
    image: {
      id: 3,
      name: 'images.jpg',
      alternativeText: '',
      caption: '',
      width: 275,
      height: 183,
      formats: {
        thumbnail: {
          ext: '.jpg',
          url: 'https://res.cloudinary.com/robitaille/image/upload/v1609194863/thumbnail_images_9ab40a756d.jpg',
          hash: 'thumbnail_images_9ab40a756d',
          mime: 'image/jpeg',
          name: 'thumbnail_images.jpg',
          path: null,
          size: 13.18,
          width: 234,
          height: 156,
          provider_metadata: {
            public_id: 'thumbnail_images_9ab40a756d',
            resource_type: 'image',
          },
        },
      },
      hash: 'images_9ab40a756d',
      ext: '.jpg',
      mime: 'image/jpeg',
      size: 17.16,
      url: 'https://res.cloudinary.com/robitaille/image/upload/v1609194863/images_9ab40a756d.jpg',
      previewUrl: null,
      provider: 'cloudinary',
      provider_metadata: {
        public_id: 'images_9ab40a756d',
        resource_type: 'image',
      },
      created_at: '2020-12-28T22:34:23.891Z',
      updated_at: '2020-12-28T22:34:23.915Z',
    },
  },
];
