export const partners = [
  {
    id: 1,
    PartnerName: 'LG Solar',
    PartnerDescription:
      "We are excited to announce that Solar Power New England is now a **Certified LG Pro**! \n\nThrough this new partnership with the best-rated solar panel manufacturer in the world, we're able to offer our customers a competitive price, for the newest, most-efficient power conversion technology available today. \n\n\n\nIf you would like a free consultation, a free look with a detailed presentation of the technology behind their award-winning Neon 2, Neon R, and Neon R *Prime* modules, our site assessments are free, and we'd be happy to work **with you** to figure out how solar could work **for you**...\n\nCall Us Today\n[Solar Power New England](mailto:contact@solarpowerne.com)\n1-207-387-0037\n\nUpdate 2022: LG Electronics has announced February 22, 2022 that it will be exiting the global solar business, winding down their solar module production beginning in the Spring of '22. We will miss these fantastic modules, but are sure that we will see more from LG in other forms akin to their many contributions toward the energy industry for the last 40+ years. \nFor more information, please see their press release [here](https://www.lg.com/us/press-release/lg-to-exit-global-solar-panel-business).\n\nFor warranty and other product related questions, you may visit the LG website [here](https://www.lg.com/us/solar/warranty), or reach out to us with your questions, via our [contact form](https://www.solarpowernewengland.com/about)\n\n\n![LGProLogo_Silver.jpg](https://res.cloudinary.com/robitaille/image/upload/v1618257978/LG_Pro_Logo_Silver_189c89b10e.jpg)\n\n",
    published_at: '2021-04-26T23:00:10.543Z',
    created_at: '2021-04-26T23:00:07.769Z',
    updated_at: '2022-07-27T19:15:38.469Z',
    slug: 'lg-solar',
    ShortDescription:
      'LG Solar - Neon 2, Neon R, and Neon R Prime Module Feature',
    Tags: 'partners, solar',
    PartnerImage: [
      {
        id: 49,
        name: 'LG Neon R',
        alternativeText: 'LG Solar Neon R',
        caption: 'LG Neon R',
        width: 5392,
        height: 3616,
        formats: {
          large: {
            ext: '.jpg',
            url: 'https://res.cloudinary.com/robitaille/image/upload/v1618259428/large_LG_Neon_R_Rochester_499229063c.jpg',
            hash: 'large_LG_Neon_R_Rochester_499229063c',
            mime: 'image/jpeg',
            name: 'large_LG Neon R Rochester.jpg',
            path: null,
            size: 239.51,
            width: 1000,
            height: 671,
            provider_metadata: {
              public_id: 'large_LG_Neon_R_Rochester_499229063c',
              resource_type: 'image',
            },
          },
          small: {
            ext: '.jpg',
            url: 'https://res.cloudinary.com/robitaille/image/upload/v1618259429/small_LG_Neon_R_Rochester_499229063c.jpg',
            hash: 'small_LG_Neon_R_Rochester_499229063c',
            mime: 'image/jpeg',
            name: 'small_LG Neon R Rochester.jpg',
            path: null,
            size: 62.01,
            width: 500,
            height: 335,
            provider_metadata: {
              public_id: 'small_LG_Neon_R_Rochester_499229063c',
              resource_type: 'image',
            },
          },
          medium: {
            ext: '.jpg',
            url: 'https://res.cloudinary.com/robitaille/image/upload/v1618259429/medium_LG_Neon_R_Rochester_499229063c.jpg',
            hash: 'medium_LG_Neon_R_Rochester_499229063c',
            mime: 'image/jpeg',
            name: 'medium_LG Neon R Rochester.jpg',
            path: null,
            size: 139.46,
            width: 750,
            height: 503,
            provider_metadata: {
              public_id: 'medium_LG_Neon_R_Rochester_499229063c',
              resource_type: 'image',
            },
          },
          thumbnail: {
            ext: '.jpg',
            url: 'https://res.cloudinary.com/robitaille/image/upload/v1618259428/thumbnail_LG_Neon_R_Rochester_499229063c.jpg',
            hash: 'thumbnail_LG_Neon_R_Rochester_499229063c',
            mime: 'image/jpeg',
            name: 'thumbnail_LG Neon R Rochester.jpg',
            path: null,
            size: 14.4,
            width: 233,
            height: 156,
            provider_metadata: {
              public_id: 'thumbnail_LG_Neon_R_Rochester_499229063c',
              resource_type: 'image',
            },
          },
        },
        hash: 'LG_Neon_R_Rochester_499229063c',
        ext: '.jpg',
        mime: 'image/jpeg',
        size: 5455.05,
        url: 'https://res.cloudinary.com/robitaille/image/upload/v1618259427/LG_Neon_R_Rochester_499229063c.jpg',
        previewUrl: null,
        provider: 'cloudinary',
        provider_metadata: {
          public_id: 'LG_Neon_R_Rochester_499229063c',
          resource_type: 'image',
        },
        created_at: '2021-04-12T20:30:29.837Z',
        updated_at: '2021-07-14T21:10:44.909Z',
      },
    ],
  },
  {
    id: 3,
    PartnerName: 'SPAN',
    PartnerDescription:
      'Span & the Smart Panel of the Future - Battery-Ready, and PV-Ready, Simplified\n\n![panel+++app.png](https://res.cloudinary.com/robitaille/image/upload/v1626274532/panel_app_ad9b58f094.png)\n\nWe are thrilled to be the first company in the State of Maine to be a Span Certified Installer. Through this partnership, we are able to bring new and existing homeowners the best, most cutting-edge, and state-of-the-art equipment available today. \n\n![Span+Certified+Installer.jpg](https://res.cloudinary.com/robitaille/image/upload/v1626274538/Span_Certified_Installer_8412538bad.jpg)\n\nSolar Power New England is now a Certified Installer and Reseller for the Span Smart Panel. Span Certified Installers have installed hundreds of Span Panels across the nation since their launch in 2019, providing homeowners with greater flexibility and control over their home energy, both on and off-grid. \n\n“Span is making home energy connected and intuitive with a smart electrical panel that makes it easier to adopt clean energy and optimize power.”\n\n“The electrical panel is an essential part of your home, interfacing with the grid, solar, battery storage, and everything you power. Get the panel that helps you achieve your energy upgrade goals while giving you better options for managing your battery backup.”\n\n\n\n#### What Separates Span From The Rest?\n\n- Monitoring and control for every circuit: The Span Smart Panel provides a fully automated and "app-monitored" main service panel solution that allows full control over each load and breaker. Did we mention the panel is breaker-agnostic? Unlike the Lumin Smart Panel, which requires use of their own expensive, branded-breakers, and a lack of true flexibility or dedication toward renewable energy, the *Span* solution makes main service panels in new homes, truly a future-ready solution. That means we can install commercially available Schnieder Electric(QO or Homeline), Eaton, or other commonly found breakers for your loads.\n- Fully Customizable Backup when paired with storage: depending on your needs, the span smart panel come with or without a built-in auto-transformer, with dedicated breaker spots for your Solar(PV), and your Home Battery(Evervolt, Powerwall, etc.) - You can plan what loads stay on, and what loads "go-out" in the event of a grid-interruption.\n- Indoor/Outdoor Rated, 100-200a\n- Now 46% lighter and 35% smaller than v1\n \n***4-6 week Lead Time for Parts/Availability*** (Updated 7.2022)\n\n\n\nIf you are building a new home, looking to purchase a home that needs an electrical upgrade, and you want to be TRULY **solar**, and/or **battery-ready**- this is the only solution you should be looking to use.\n\n[Contact us today with details about your project(s)](mailto:contact@solarpowerne.com)\n\n![certified+Installer+logo+white+with+background.jpg](https://res.cloudinary.com/robitaille/image/upload/v1626274527/certified_Installer_logo_white_with_background_33326d6c57.jpg)',
    published_at: '2021-07-14T15:13:08.553Z',
    created_at: '2021-07-14T14:44:35.547Z',
    updated_at: '2022-07-27T17:47:59.322Z',
    slug: 'span',
    ShortDescription:
      'Span Certified Installer, Span Smart Panel, AI-Driven Intelligence and real-time control - Solar Power New England, your Maine Certified Installer of the Span solution',
    Tags: 'Devices, Storage, Smart Panel, Energy Monitoring',
    PartnerImage: [
      {
        id: 62,
        name: 'panel+++app.png',
        alternativeText: '',
        caption: '',
        width: 500,
        height: 817,
        formats: {
          small: {
            ext: '.png',
            url: 'https://res.cloudinary.com/robitaille/image/upload/v1626274533/small_panel_app_ad9b58f094.png',
            hash: 'small_panel_app_ad9b58f094',
            mime: 'image/png',
            name: 'small_panel+++app.png',
            path: null,
            size: 55.27,
            width: 306,
            height: 500,
            provider_metadata: {
              public_id: 'small_panel_app_ad9b58f094',
              resource_type: 'image',
            },
          },
          medium: {
            ext: '.png',
            url: 'https://res.cloudinary.com/robitaille/image/upload/v1626274533/medium_panel_app_ad9b58f094.png',
            hash: 'medium_panel_app_ad9b58f094',
            mime: 'image/png',
            name: 'medium_panel+++app.png',
            path: null,
            size: 106.06,
            width: 459,
            height: 750,
            provider_metadata: {
              public_id: 'medium_panel_app_ad9b58f094',
              resource_type: 'image',
            },
          },
          thumbnail: {
            ext: '.png',
            url: 'https://res.cloudinary.com/robitaille/image/upload/v1626274532/thumbnail_panel_app_ad9b58f094.png',
            hash: 'thumbnail_panel_app_ad9b58f094',
            mime: 'image/png',
            name: 'thumbnail_panel+++app.png',
            path: null,
            size: 9.07,
            width: 95,
            height: 156,
            provider_metadata: {
              public_id: 'thumbnail_panel_app_ad9b58f094',
              resource_type: 'image',
            },
          },
        },
        hash: 'panel_app_ad9b58f094',
        ext: '.png',
        mime: 'image/png',
        size: 93.12,
        url: 'https://res.cloudinary.com/robitaille/image/upload/v1626274532/panel_app_ad9b58f094.png',
        previewUrl: null,
        provider: 'cloudinary',
        provider_metadata: {
          public_id: 'panel_app_ad9b58f094',
          resource_type: 'image',
        },
        created_at: '2021-07-14T14:55:34.432Z',
        updated_at: '2021-07-14T14:55:34.439Z',
      },
    ],
  },
];
